//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class author
    {
        public int id { get; set; }
        [DisplayName("Name:")]
        public string name { get; set; }
        [DisplayName("Address:")]
        public string address { get; set; }
        [DisplayName("Phone:")]
        public string phone { get; set; }
    }
}
