//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;

    public partial class category
    {
        public int id { get; set; }
        public string catname { get; set; }
        public string status { get; set; }
    }
}
