//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_ASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuebook
    {
        public int id { get; set; }
        public int m_id { get; set; }
        public int book_id { get; set; }
        public System.DateTime issuedate { get; set; }
        public System.DateTime returndate { get; set; }
    }
}
